spring:
  application:
    name: games-service
  config:
    import: optional:configserver:http://localhost:8888

game:
  external:
    service:
      games-api-url: http://localhost:9085
      user-service-url: http://localhost:8090